<?php
session_start();
include('check-login.php');
include('dbstring.php');
include_once('transport-utils.php');
if(!transport_is_admin()){ http_response_code(403); exit('Administrator access required.'); }
transport_ensure_tables($con);
function tsa($value){ return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
$message = '';
$actor = isset($_SESSION['USERID']) ? $_SESSION['USERID'] : '';
if(isset($_POST['assign_transport'])){
    list($ok,$message)=transport_assign_student($con,trim((string)$_POST['userid']),trim((string)$_POST['routeid']),trim((string)$_POST['stopid']),$actor);
}
if(isset($_POST['assign_transport_bulk'])){
    list($ok,$message)=transport_assign_students_bulk($con,isset($_POST['userids'])?$_POST['userids']:array(),trim((string)$_POST['routeid']),trim((string)$_POST['stopid']),$actor);
}
$routes=array();$result=mysqli_query($con,"SELECT tr.routeid,tr.routename,tr.fee,v.vehiclename,v.capacity,(SELECT COUNT(*) FROM tblstudenttransport st WHERE st.routeid=tr.routeid AND st.status='active') assigned FROM tbltransportroute tr LEFT JOIN tbltransportvehicle v ON v.vehicleid=tr.vehicleid WHERE tr.status='active' ORDER BY tr.routename");if($result)while($row=mysqli_fetch_assoc($result))$routes[]=$row;
$stops=array();$result=mysqli_query($con,"SELECT * FROM tbltransportstop WHERE status='active' ORDER BY routeid,sortorder,stopname");if($result)while($row=mysqli_fetch_assoc($result))$stops[]=$row;
$students=array();$result=mysqli_query($con,"SELECT userid,CONCAT_WS(' ',firstname,othernames,surname) AS name FROM tblsystemuser WHERE systemtype='Student' AND status='active' ORDER BY firstname,surname");if($result)while($row=mysqli_fetch_assoc($result))$students[]=$row;
$assigned=array();$result=mysqli_query($con,"SELECT st.*,CONCAT_WS(' ',su.firstname,su.othernames,su.surname) AS studentname,tr.routename,ts.stopname FROM tblstudenttransport st INNER JOIN tblsystemuser su ON su.userid=st.userid LEFT JOIN tbltransportroute tr ON tr.routeid=st.routeid LEFT JOIN tbltransportstop ts ON ts.stopid=st.stopid WHERE st.status='active' ORDER BY tr.routename,studentname");if($result)while($row=mysqli_fetch_assoc($result))$assigned[]=$row;
?>
<!doctype html><html><head><?php include('links.php');?><title>Student Transport Assignment</title><style>
body{background:#f4f8fb;font-family:Arial;color:#17314b}.tsa{max-width:1050px;margin:25px auto;background:#fff;padding:24px;border-radius:16px}.form{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.form select{padding:10px;background:#fff;color:#102a43;border:1px solid #7893aa;border-radius:7px}.form button{background:#087443;color:#fff;border:0;border-radius:8px;padding:11px}.bulk{margin-top:24px;padding:18px;border:1px solid #dce6ee;border-radius:12px;background:#fbfdff}.bulk h2{margin-top:0}.student-tools{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}.student-tools input{flex:1 1 260px;padding:10px;border:1px solid #7893aa;border-radius:7px}.student-tools button{padding:9px 12px;border:0;border-radius:7px;background:#e7f1fa;color:#17314b;cursor:pointer}.student-list{max-height:310px;overflow:auto;border:1px solid #dce6ee;border-radius:8px;background:#fff}.student-choice{display:block;padding:9px 12px;border-bottom:1px solid #edf2f6;cursor:pointer}.student-choice:last-child{border-bottom:0}.student-choice input{margin-right:9px}.bulk-count{font-size:13px;color:#48617a}.tsa table{width:100%;border-collapse:collapse;margin-top:20px}.tsa td,.tsa th{padding:9px;border-bottom:1px solid #dce6ee;text-align:left}@media(max-width:700px){.tsa{margin:8px;padding:14px}.form{grid-template-columns:1fr}}
</style></head><body><main class="tsa"><p><a href="transport-management.php">← Transport setup</a></p><h1>Student Transport Assignment</h1><p>Assign one pupil or several pupils to an active route and pickup stop.</p><?php if($message!==''){ ?><p><?php echo tsa($message); ?></p><?php } ?>
<h2>Assign One Student</h2><form method="post" class="form"><select name="userid" required><option value="">Choose student</option><?php foreach($students as $student){ ?><option value="<?php echo tsa($student['userid']); ?>"><?php echo tsa($student['name'].' — '.$student['userid']); ?></option><?php } ?></select><select name="routeid" required><option value="">Choose route</option><?php foreach($routes as $route){ ?><option value="<?php echo tsa($route['routeid']); ?>"><?php echo tsa($route['routename'].' ('.$route['assigned'].'/'.$route['capacity'].')'); ?></option><?php } ?></select><select name="stopid"><option value="">No stop selected</option><?php foreach($stops as $stop){ ?><option value="<?php echo tsa($stop['stopid']); ?>"><?php echo tsa($stop['stopname'].' — '.$stop['pickuptime']); ?></option><?php } ?></select><button name="assign_transport">Save Student Transport</button></form>
<section class="bulk"><h2>Bulk Assign Students</h2><p>Select as many pupils as needed, then choose one route and pickup stop. The system checks capacity before saving.</p><form method="post"><div class="form"><select name="routeid" required><option value="">Choose route</option><?php foreach($routes as $route){ ?><option value="<?php echo tsa($route['routeid']); ?>"><?php echo tsa($route['routename'].' ('.$route['assigned'].'/'.$route['capacity'].')'); ?></option><?php } ?></select><select name="stopid"><option value="">No stop selected</option><?php foreach($stops as $stop){ ?><option value="<?php echo tsa($stop['stopid']); ?>"><?php echo tsa($stop['stopname'].' — '.$stop['pickuptime']); ?></option><?php } ?></select><button name="assign_transport_bulk">Assign Selected Students</button></div><div class="student-tools"><input type="search" id="bulk-student-search" placeholder="Search pupil by name or ID"><button type="button" id="select-visible-students">Select visible</button><button type="button" id="clear-students">Clear selection</button><span class="bulk-count" id="bulk-student-count">0 selected</span></div><div class="student-list" id="bulk-student-list"><?php foreach($students as $student){ $searchText=strtolower($student['name'].' '.$student['userid']); ?><label class="student-choice" data-search="<?php echo tsa($searchText); ?>"><input class="bulk-student" type="checkbox" name="userids[]" value="<?php echo tsa($student['userid']); ?>"><?php echo tsa($student['name'].' — '.$student['userid']); ?></label><?php } ?></div></form></section>
<h2>Active Student Transport List</h2><table><tr><th>Student</th><th>Route</th><th>Pickup Stop</th></tr><?php foreach($assigned as $assignment){ ?><tr><td><?php echo tsa($assignment['studentname']); ?></td><td><?php echo tsa($assignment['routename']); ?></td><td><?php echo tsa($assignment['stopname']); ?></td></tr><?php } ?></table></main><script>
(function(){var search=document.getElementById('bulk-student-search'),items=[].slice.call(document.querySelectorAll('.student-choice')),boxes=[].slice.call(document.querySelectorAll('.bulk-student')),count=document.getElementById('bulk-student-count');function update(){count.textContent=boxes.filter(function(box){return box.checked;}).length+' selected';}search.addEventListener('input',function(){var term=search.value.toLowerCase();items.forEach(function(item){item.style.display=item.getAttribute('data-search').indexOf(term)!==-1?'block':'none';});});boxes.forEach(function(box){box.addEventListener('change',update);});document.getElementById('select-visible-students').addEventListener('click',function(){items.forEach(function(item){if(item.style.display!=='none')item.querySelector('input').checked=true;});update();});document.getElementById('clear-students').addEventListener('click',function(){boxes.forEach(function(box){box.checked=false;});update();});update();})();
</script></body></html>
