<?php
if(!function_exists('transport_is_admin')){function transport_is_admin(){return isset($_SESSION['ACCESSLEVEL'])&&$_SESSION['ACCESSLEVEL']==='administrator';}}
if(!function_exists('transport_id')){function transport_id($prefix){return $prefix.strtoupper(substr(sha1(uniqid('',true)),0,18));}}
if(!function_exists('transport_ensure_tables')){function transport_ensure_tables($con){
@mysqli_query($con,"CREATE TABLE IF NOT EXISTS tbltransportvehicle(vehicleid VARCHAR(50) PRIMARY KEY,vehiclename VARCHAR(120) NOT NULL,registrationno VARCHAR(80) NOT NULL,capacity INT NOT NULL DEFAULT 0,driverid VARCHAR(100) NOT NULL DEFAULT '',assistantid VARCHAR(100) NOT NULL DEFAULT '',status VARCHAR(20) NOT NULL DEFAULT 'active',createdby VARCHAR(100) NOT NULL DEFAULT '',createdat DATETIME NOT NULL,UNIQUE KEY uq_registrationno(registrationno)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
@mysqli_query($con,"CREATE TABLE IF NOT EXISTS tbltransportroute(routeid VARCHAR(50) PRIMARY KEY,routename VARCHAR(150) NOT NULL,vehicleid VARCHAR(50) NOT NULL DEFAULT '',fee DECIMAL(12,2) NOT NULL DEFAULT 0,status VARCHAR(20) NOT NULL DEFAULT 'active',createdby VARCHAR(100) NOT NULL DEFAULT '',createdat DATETIME NOT NULL,UNIQUE KEY uq_routename(routename),KEY idx_vehicle(vehicleid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
@mysqli_query($con,"CREATE TABLE IF NOT EXISTS tbltransportstop(stopid VARCHAR(50) PRIMARY KEY,routeid VARCHAR(50) NOT NULL,stopname VARCHAR(150) NOT NULL,pickuptime VARCHAR(20) NOT NULL DEFAULT '',sortorder INT NOT NULL DEFAULT 0,status VARCHAR(20) NOT NULL DEFAULT 'active',createdat DATETIME NOT NULL,KEY idx_route(routeid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
@mysqli_query($con,"CREATE TABLE IF NOT EXISTS tblstudenttransport(assignmentid VARCHAR(50) PRIMARY KEY,userid VARCHAR(100) NOT NULL,routeid VARCHAR(50) NOT NULL,stopid VARCHAR(50) NOT NULL DEFAULT '',status VARCHAR(20) NOT NULL DEFAULT 'active',assignedby VARCHAR(100) NOT NULL DEFAULT '',assignedat DATETIME NOT NULL,UNIQUE KEY uq_student_transport(userid),KEY idx_route(routeid,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}}
if(!function_exists('transport_route_capacity')){function transport_route_capacity($con,$routeId){$r=mysqli_query($con,"SELECT v.capacity,(SELECT COUNT(*) FROM tblstudenttransport st WHERE st.routeid=tr.routeid AND st.status='active') assigned FROM tbltransportroute tr LEFT JOIN tbltransportvehicle v ON v.vehicleid=tr.vehicleid WHERE tr.routeid='".mysqli_real_escape_string($con,$routeId)."' LIMIT 1");return $r?mysqli_fetch_assoc($r):null;}}
if(!function_exists('transport_assign_student')){function transport_assign_student($con,$studentId,$routeId,$stopId,$actor){transport_ensure_tables($con);$cap=transport_route_capacity($con,$routeId);if(!$cap)return array(false,'The selected route was not found.');if((int)$cap['capacity']>0&&(int)$cap['assigned']>=(int)$cap['capacity'])return array(false,'This route has reached vehicle capacity.');$s=mysqli_real_escape_string($con,$studentId);$r=mysqli_real_escape_string($con,$routeId);$p=mysqli_real_escape_string($con,$stopId);$a=mysqli_real_escape_string($con,$actor);$id=transport_id('TRA_');$ok=mysqli_query($con,"INSERT INTO tblstudenttransport(assignmentid,userid,routeid,stopid,status,assignedby,assignedat) VALUES('$id','$s','$r','$p','active','$a',NOW()) ON DUPLICATE KEY UPDATE routeid='$r',stopid='$p',status='active',assignedby='$a',assignedat=NOW()");return array($ok,$ok?'Student transport assignment saved.':'Could not save the transport assignment.');}}
if(!function_exists('transport_assign_students_bulk')){function transport_assign_students_bulk($con,$studentIds,$routeId,$stopId,$actor){
transport_ensure_tables($con);$routeId=trim((string)$routeId);$stopId=trim((string)$stopId);$studentIds=is_array($studentIds)?$studentIds:array();$studentIds=array_values(array_unique(array_filter(array_map('trim',$studentIds))));
if($routeId===''||empty($studentIds))return array(false,'Choose a route and at least one student.');
$routeEsc=mysqli_real_escape_string($con,$routeId);$stopEsc=mysqli_real_escape_string($con,$stopId);$actorEsc=mysqli_real_escape_string($con,(string)$actor);
$routeRes=mysqli_query($con,"SELECT tr.routeid,v.capacity FROM tbltransportroute tr LEFT JOIN tbltransportvehicle v ON v.vehicleid=tr.vehicleid WHERE tr.routeid='$routeEsc' AND tr.status='active' LIMIT 1");$route=$routeRes?mysqli_fetch_assoc($routeRes):null;if(!$route)return array(false,'The selected route was not found.');
if($stopId!==''){ $stopRes=mysqli_query($con,"SELECT stopid FROM tbltransportstop WHERE stopid='$stopEsc' AND routeid='$routeEsc' AND status='active' LIMIT 1");if(!$stopRes||mysqli_num_rows($stopRes)===0)return array(false,'Choose a pickup stop that belongs to the selected route.'); }
$quoted=array();foreach($studentIds as $studentId)$quoted[]="'".mysqli_real_escape_string($con,$studentId)."'";$idList=implode(',',$quoted);
$studentRes=mysqli_query($con,"SELECT userid FROM tblsystemuser WHERE systemtype='Student' AND status='active' AND userid IN ($idList)");$valid=array();if($studentRes)while($row=mysqli_fetch_assoc($studentRes))$valid[$row['userid']]=true;if(count($valid)!==count($studentIds))return array(false,'One or more selected students are no longer active. Refresh the page and try again.');
$currentRes=mysqli_query($con,"SELECT userid,routeid FROM tblstudenttransport WHERE userid IN ($idList) AND status='active'");$current=array();if($currentRes)while($row=mysqli_fetch_assoc($currentRes))$current[$row['userid']]=$row['routeid'];$newSlots=0;foreach($studentIds as $studentId){if(!isset($current[$studentId])||$current[$studentId]!==$routeId)$newSlots++;}
$capacity=(int)$route['capacity'];if($capacity>0){$countRes=mysqli_query($con,"SELECT COUNT(*) AS assigned FROM tblstudenttransport WHERE routeid='$routeEsc' AND status='active'");$assigned=$countRes?(int)mysqli_fetch_assoc($countRes)['assigned']:0;if($assigned+$newSlots>$capacity)return array(false,'This bulk assignment needs '.$newSlots.' seat(s), but the route has only '.max(0,$capacity-$assigned).' seat(s) available.');}
if(!mysqli_begin_transaction($con))return array(false,'Could not start the bulk assignment.');foreach($studentIds as $studentId){$studentEsc=mysqli_real_escape_string($con,$studentId);$assignmentId=transport_id('TRA_');$ok=mysqli_query($con,"INSERT INTO tblstudenttransport(assignmentid,userid,routeid,stopid,status,assignedby,assignedat) VALUES('$assignmentId','$studentEsc','$routeEsc','$stopEsc','active','$actorEsc',NOW()) ON DUPLICATE KEY UPDATE routeid='$routeEsc',stopid='$stopEsc',status='active',assignedby='$actorEsc',assignedat=NOW()");if(!$ok){mysqli_rollback($con);return array(false,'No student was assigned because the bulk save failed.');}}
mysqli_commit($con);return array(true,count($studentIds).' student(s) assigned to transport.');
}}
?>
