<?php require_once("dbstring.php"); require_once("website-content-utils.php"); $apsWebsiteContent=aps_website_content($con); ob_start(); ?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Awuah Preparatory School — a nurturing place for curious minds, confident learners and bright futures.">
  <title>Awuah Preparatory School | Brighten the Corner</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="css/awuah-school-site.css">
</head>
<body>
  <div class="topbar"><div class="shell"><span>Welcome to the Awuah Preparatory School community.</span><strong>Enquiries &amp; school visits are welcome.</strong></div></div>
  <div class="nav-wrap"><nav class="nav shell" aria-label="Main navigation">
    <a class="brand" href="#home" aria-label="Awuah Preparatory School home"><span class="brand-mark">APS</span><span class="brand-copy"><strong>Awuah Preparatory</strong><span>Brighten the corner</span></span></a>
    <button class="menu-button" type="button" aria-label="Open navigation" aria-expanded="false">☰</button>
    <div class="nav-links"><a href="#about">About us</a><a href="#programmes">Learning</a><a href="#admissions">Admissions</a><a href="alumni.php">Old Students</a><a href="announcements.php">News</a><a href="#contact">Contact</a><a class="nav-portal" href="parent-portal.php">Portal login ↗</a></div>
  </nav></div>
  <main>
    <section class="hero" id="home"><img class="hero-image" src="images/awuah-preparatory-hero.png" alt="Pupils arriving at a welcoming school campus"><div class="shell"><div class="hero-copy"><span class="eyebrow">A place to belong and become</span><h1>Small steps.<br>Bright futures.</h1><p>Awuah Preparatory School is a warm learning community where every child is known, encouraged and inspired to grow with confidence.</p><div class="hero-actions"><a class="button gold" href="#admissions">Begin an enquiry</a><a class="button outline" href="#programmes">Explore learning</a></div><div class="hero-note"><b>✦</b> Building strong foundations for life-long learning.</div></div></div><aside class="hero-card"><small>Our guiding belief</small><p>Every child deserves to be seen, supported and challenged.</p></aside></section>
    <section class="intro" id="about"><div class="shell intro-grid"><div class="intro-art" aria-hidden="true"><div class="book"></div></div><div class="intro-copy"><span class="eyebrow">Our school</span><h2>Learning with purpose, character and joy.</h2><p>We believe a great primary education does more than teach children what to think. It equips them to ask thoughtful questions, work with others and approach the world with confidence and kindness.</p><p>At Awuah Preparatory School, pupils learn in a supportive environment where high expectations are paired with patient guidance and meaningful encouragement.</p><div class="values"><div class="value"><span>✦</span><strong>Curiosity</strong></div><div class="value"><span>♥</span><strong>Character</strong></div><div class="value"><span>↗</span><strong>Confidence</strong></div></div></div></div></section>
    <section class="programmes" id="programmes"><div class="shell"><div class="section-heading"><span class="eyebrow">Our learning journey</span><h2>A strong start at every stage.</h2><p>Thoughtful teaching, engaging experiences and caring support help each pupil develop the essential knowledge and habits for the next step.</p></div><div class="programme-grid"><article class="programme"><span class="programme-number">01</span><h3>Early Years</h3><p>Playful, caring beginnings that nurture language, independence, social confidence and a love of discovering new things.</p></article><article class="programme"><span class="programme-number">02</span><h3>Lower Primary</h3><p>Secure foundations in literacy, numeracy and inquiry—helping young learners become enthusiastic and capable pupils.</p></article><article class="programme"><span class="programme-number">03</span><h3>Upper Primary</h3><p>Deeper thinking, personal responsibility and rich learning experiences that prepare children confidently for their next chapter.</p></article></div></div></section>
    <section class="why"><div class="shell why-grid"><div><div class="section-heading"><span class="eyebrow">The Awuah difference</span><h2>More than lessons. A community that helps children flourish.</h2><p>Families need a school that values both achievement and the whole child. Our approach brings these together, every day.</p></div><div class="feature-list"><article class="feature"><span class="feature-icon">◌</span><div><h3>Children at the centre</h3><p>Each learner is encouraged as an individual, with the care and attention they need to make meaningful progress.</p></div></article><article class="feature"><span class="feature-icon">⌁</span><div><h3>Learning that feels alive</h3><p>We make space for questions, practical exploration, creativity and the satisfaction of mastering something new.</p></div></article><article class="feature"><span class="feature-icon">⌂</span><div><h3>Partnership with families</h3><p>Open communication and shared purpose help home and school work together for every child.</p></div></article></div></div><aside class="quote"><p>“The best education gives children both roots and wings.”</p><span>Our promise to every Awuah learner</span></aside></div></section>
    <section class="admissions" id="admissions"><div class="shell admission-grid"><div><span class="eyebrow">Admissions enquiries</span><h2>Let’s begin your child’s Awuah story.</h2><p>We would be delighted to welcome you, answer your questions and help you learn more about joining our school community.</p><div class="steps"><div class="step"><b>1</b> Send us a short enquiry</div><div class="step"><b>2</b> Arrange a school visit</div><div class="step"><b>3</b> Receive admissions guidance</div></div></div><form class="admission-card" id="enquiry-form"><h3>Start an enquiry</h3><p>Complete this form and our admissions team will be in touch.</p><label for="parent-name">Parent or guardian name</label><input id="parent-name" name="parent-name" required placeholder="Your full name"><label for="phone">Phone number</label><input id="phone" name="phone" required placeholder="e.g. 024 000 0000"><label for="message">How can we help?</label><textarea id="message" name="message" placeholder="Tell us the class level you are interested in."></textarea><button class="button gold" type="submit">Send enquiry</button></form></div></section>
    <section class="contact" id="contact"><div class="shell"><div class="section-heading"><span class="eyebrow">Keep in touch</span><h2>We would love to hear from you.</h2><p>Contact the school office for admissions information, a visit, or any question about Awuah Preparatory School.</p></div><div class="contact-grid"><div class="contact-card"><span>⌂</span><h3>Visit the school</h3><p>Arrange a convenient time with the school office for a warm welcome and guided visit.</p></div><div class="contact-card"><span>☏</span><h3>Call the office</h3><p>Contact details can be added here once the school’s preferred phone number is confirmed.</p></div><div class="contact-card"><span>✉</span><h3>Send an email</h3><p>Set the school’s admissions email address here to receive parent enquiries directly.</p></div></div></div></section>
  </main>
  <footer><div class="shell footer-inner"><div><strong>Awuah Preparatory School</strong> &nbsp;·&nbsp; Brighten the Corner</div><div>© <span id="year"></span> Awuah Preparatory School. All rights reserved.</div></div></footer>
  <div class="toast" role="status" aria-live="polite">Thank you. Your enquiry has been received. The school office will be in touch shortly.</div>
  <script>
    const menuButton = document.querySelector('.menu-button'); const navLinks = document.querySelector('.nav-links');
    menuButton.addEventListener('click', () => { const open = navLinks.classList.toggle('open'); menuButton.setAttribute('aria-expanded', open); menuButton.textContent = open ? '×' : '☰'; });
    document.querySelectorAll('.nav-links a').forEach(link => link.addEventListener('click', () => { navLinks.classList.remove('open'); menuButton.setAttribute('aria-expanded', 'false'); menuButton.textContent = '☰'; }));
    document.getElementById('year').textContent = new Date().getFullYear();
    document.getElementById('enquiry-form').addEventListener('submit', event => { event.preventDefault(); const toast = document.querySelector('.toast'); toast.classList.add('show'); event.currentTarget.reset(); setTimeout(() => toast.classList.remove('show'), 5000); });
  </script>
</body>
</html><?php $apsWebsiteOutput=ob_get_clean(); $apsWebsiteOutput=str_replace(array("Welcome to the Awuah Preparatory School community.","Small steps.<br>Bright futures.","Awuah Preparatory School is a warm learning community where every child is known, encouraged and inspired to grow with confidence."),array(aps_website_escape($apsWebsiteContent["welcome_message"]),nl2br(aps_website_escape(str_replace("|",PHP_EOL,$apsWebsiteContent["hero_title"]))),aps_website_escape($apsWebsiteContent["hero_text"])),$apsWebsiteOutput); echo $apsWebsiteOutput; ?>
